version: "3.8"

services:
  app1: &app1
    build:
      context: .
      dockerfile: Dockerfile
      target: release1
    environment: &env_app1
      APP_ENV: production
      APP_DEBUG: false
      LOG_CHANNEL: null
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 6432
      DB_DATABASE: rinha
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PORT: 9997
    network_mode: host
    depends_on:
    - postgres
    command: ["migrate_and_release"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.75GB'

  app2:
    <<: *app1
    build:
      context: .
      dockerfile: Dockerfile
      target: release2
    depends_on:
    - app1
    environment:
      <<: *env_app1
      PORT: 9998
    command: ["release"]

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    network_mode: host
    depends_on:
    - app1
    - app2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.7GB'

  pgbouncer:
    build:
      context: .
      dockerfile: Dockerfile.pgbouncer
    network_mode: host
    depends_on:
    - postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
